### ISSUE TITLE
File Type Support

### ISSUE THREAD

**Issue by puerco** [kubernetes-sigs/bom#10]
#### What would you like to be added:

SPDX defines an optional `FileType` field. This field can take any of these values:

`SOURCE | BINARY | ARCHIVE | APPLICATION | AUDIO | IMAGE | TEXT | VIDEO | DOCUMENTATION | SPDX | OTHER`

We could do a rapid scan of the files and do a quick determination of the type

Ref:  https://spdx.github.io/spdx-spec/file-information/#83-file-type-field

#### Why is this needed:

Scanning and determining this value results in a richer SBOM.

**Comment by cpanato** [comment]
i will take this
/assign
