### ISSUE TITLE
Provide support for CycloneDX 

### ISSUE THREAD

**Issue by VinodAnandan** [kubernetes-sigs/bom#100]
#### What would you like to be added:
Provide support and generate CycloneDX SBOM.

#### Why is this needed:
OWASP CycloneDX is a lightweight Software Bill of Materials (SBOM) standard designed to use in the application security contexts and supply chain component analysis. CycloneDX is an OWASP flagship project ( https://owasp.org/www-project-cyclonedx ). The Open Web Application Security Project is a non-profit foundation that works to improve the security of software. 

CycloneDX is already supported by many security vendors and projects ( https://cyclonedx.org/about/supporters ). It is also recommended in the Technology Radar Volume 26 ( https://www.thoughtworks.com/radar/platforms?blipid=202203034 )

Related discussion links:
https://app.slack.com/client/T09NY5SBT/C2C40FMNF/thread/C2C40FMNF-1637756090.238600
https://twitter.com/puerco/status/1414786491776212992

Cc: @puerco, @coderpatros, @stevespringett, @nscuro

**Comment by stevespringett** [comment]
Any update on this? Is there anything the OWASP or CycloneDX community can do to move this forward?

**Comment by VinodAnandan** [comment]
@puerco: gentle reminder

**Comment by benjaminguttmann-avtq** [comment]
We would be also interested in a cycloneDX support, is there any update or anything we could help with?

**Comment by cpanato** [comment]
Hello, @costica11; we are trying to prioritize work for this project while we have other projects and company work.
I don't see we will work on this in the near time, but you also can contribute to this project and open a pull request to add this feature. We will be happy to review it.
