### ISSUE TITLE
Support additional output formats for SPDX

### ISSUE THREAD

**Issue by jdolitsky** [kubernetes-sigs/bom#103]
From https://spdx.dev/resources/use/#documents:

> SPDX Documents can use one of five file formats, tag/value (.spdx), JSON(.spdx.json), YAML(.spdx.yml), RDF/xml(spdx.rdf) and spreadsheets (.xls).

On `bom generate`, would like to be able to specify `--format=json` to get an SPDX document in JSON format.

**Comment by puerco** [comment]
We have talked about this so much that I can't believe we did not have an issue for it already (both for ingestion and output)

**Comment by jdolitsky** [comment]
Opened https://github.com/kubernetes-sigs/bom/pull/104 for the output side
