### ISSUE TITLE
SPDX 2.3 Support 

### ISSUE THREAD

**Issue by puerco** [kubernetes-sigs/bom#111]
#### SPDX 2.3 Support :tada: 

The final SPDX 2.3 spec is expected to land before the end of July '22. `bom` should support the new spec.

### Why is this needed:

We want to enable our users to generate SBOMs in the latest version of the spec. Yet, there are still open questions on what to do with 2.2.x support. My first thought was to drop support 2.2 generation altogether but now, with the support of serializers landing last week it is feasible to support both.

**Comment by puerco** [comment]
Open call on slack for interested parties to comment on the issue:
https://kubernetes.slack.com/archives/C2C40FMNF/p1655311658415219

**Comment by jeremyrickard** [comment]
If we drop support for 2.2, will the SBOMs we created for 1.23 and 1.24 will be usable by the `bom` tool? If not, we probably need to keep 2.2 support until those releases are no longer in support?

**Comment by puerco** [comment]
The idea would be only drop 2.2.x for generating documents while keeping it for ingesting (bom document outline/query etc)

**Comment by jeremyrickard** [comment]
Oh i totally missed the specifier about generation. I think this would be fine then.
