### ISSUE TITLE
bom runtime error

### ISSUE THREAD

**Issue by mdeicas** [kubernetes-sigs/bom#127]
#### What happened:

Running `bom generate` on the repository https://github.com/lumjjb/sample-golang-prov fails with a runtime error using the latest commit of bom. 

The error occurred both when running in a github action and when running locally. Link to the github action logs: https://github.com/lumjjb/sample-golang-prov/runs/7026978132?check_suite_focus=true#:~:text=level%3Dinfo%20msg%3D%22Got,with%20exit%20code%202

#### How to reproduce it (as minimally and precisely as possible):
Clone the `sample-golang-prov` repository and run `bom generate -n "http://www.example.com/binary.spdx" -o "binary.spdx" .`. 

#### Anything else we need to know?:
The error does not occur when using bom at commit `5cfc466ecf53`.

#### Environment:
- OS: Ubuntu 20.04.4 (for the github runner)

**Comment by sbs2001** [comment]
Just triaged this. The error is present since https://github.com/kubernetes-sigs/bom/commit/c1f1fa302fc728f94f87dc34448a384d13ef06c0 . The bug might be in the latest https://github.com/google/licenseclassifier .

**Comment by saschagrunert** [comment]
A fix is already WIP in https://github.com/google/licenseclassifier/pull/44

For now I agree that we should revert and will propose that tomorrow.
