### ISSUE TITLE
build a distroless base image to be used for bom based on apko and melange

### ISSUE THREAD

**Issue by developer-guy** [kubernetes-sigs/bom#137]
#### What would you like to be added:

Based on the [comment](https://github.com/kubernetes-sigs/bom/pull/136#issuecomment-1183462590) that @puerco did, it'd be better to have a base image for bom tool that includes all the necessary packages such as go, git, etc. The proper way of doing it is that use a tech stack including apko[^1] and melange[^2].

cc: @justaugustus @kaniini @imjasonh @cpanato 

#### Why is this needed:

To provide a proper base image for bom tool that fits its needs.

[^1]: https://github.com/chainguard-dev/apko
[^2]: https://github.com/chainguard-dev/melange

https://github.com/kubernetes-sigs/bom/issues/137#tasklist-block-8bf5c235-6cc1-4122-9c77-166ed8434917

**Comment by developer-guy** [comment]
This might help us 👇

> https://github.com/chainguard-dev/hello-melange-apko

cc: @jdolitsky @puerco

**Comment by imjasonh** [comment]
If we could enumerate the packages that `bom` needs that would be helpful. Common things like `go` and `git` are already available as apk packages and should be very easy to bundle into an image using `apko`. `melange` should only be necessary if there's other code we'd depend on that isn't already available as an apk.

Does `bom` require Git to fetch Go modules? e.g., does it run `go get`? It might not need more than `go` to work.

**Comment by jdolitsky** [comment]
melange would be required to get `bom` into APK format if wanting to use apko to build the image

**Comment by imjasonh** [comment]
I thought the plan was to make a base image that contained all the things `bom` needed, then use `ko` to build `bom` on top of that base.

You could also use melange to build `bom` as an apk and use `apko` to stitch it into an image, but I'm not immediately sure what the benefit of that is over using `ko` and `apko`.

**Comment by jdolitsky** [comment]
> I thought the plan was to make a base image that contained all the things bom needed, then use ko to build bom on top of that base

Didn't see any mention of ko, but that would work too 😄  In fact, that would add the benefit of surfacing an SBOM from this package (no way to do this in melange currently).

**Comment by developer-guy** [comment]
I've created PR to create a base image to be used for debugging purposes in ko, and we can achieve the same one in _bom_ tool as well:

_https://github.com/google/go-containerregistry/pull/1454_

**Comment by developer-guy** [comment]
kindly ping @cpanato @saschagrunert

**Comment by saschagrunert** [comment]
I don't think we require git and go as runtime dependency for bom (this is worth a second look).

**Comment by cpanato** [comment]
no it does not need afaik

**Comment by developer-guy** [comment]
Unfortunately, the problem still exists, to reproduce the same issue here[^1]:

1. replace the base image definition defined in .ko.yaml with: `cgr.dev/chainguard/static:latest`
2. build the container image by simply running: `KO_DOCKER_REPO=ko.local BOM_LDFLAGS= ko build -B ./cmd/bom`
3. run the image on the same directory of the bom project: `docker container run --rm -v $(pwd):/work -w /work ko.local/bom:latest generate .`
4. You will get an error something like the following:
<img width="1531" alt="Screen Shot 2022-11-21 at 6 50 29 PM" src="https://user-images.githubusercontent.com/16693043/203100105-74497c02-bbd8-4271-a62c-f7790e5ddf8f.png">


[^1]: https://github.com/kubernetes-sigs/bom/issues/135

**Comment by imjasonh** [comment]
Does `bom` expect the `go` executable to be present? The "`go executbale not found`" error sounds suspicious. If so, basing its image on `static` will be a problem. Can you try basing it on `golang` and see if that helps?

**Comment by developer-guy** [comment]
> Does bom expect the go executable to be present?
yep, this is why we set the current base image of the bom project as _ ghcr.io/chainguard-images/go:latest_ [here](https://github.com/kubernetes-sigs/bom/blob/main/.ko.yaml#L1).

**Comment by developer-guy** [comment]
kindly ping folx 👋

**Comment by developer-guy** [comment]
kindly ping folx ☝️ I did a similar issue on the ko project side. 

> _https://github.com/google/go-containerregistry/pull/1454_

**Comment by saschagrunert** [comment]
Do we have any volunteer from @kubernetes-sigs/release-engineering which can provide us an overview how the `git` binary is required by the bom golang code? I highly suspect that it relates to https://github.com/kubernetes-sigs/release-sdk/issues/4

**Comment by developer-guy** [comment]
not git, bom requires go executable ☝️ @saschagrunert

**Comment by developer-guy** [comment]
I'm still interested in doing this, folx.
