### ISSUE TITLE
Publish container image per release

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/bom#171]
#### What would you like to be added:
A container image per release containing the statically linked binary for convenient usage. 
#### Why is this needed:
It would make usage of the bom tool easier in environments which support containers but not directly golang.

**Comment by cpanato** [comment]
Did you read my mind?
Im working on this


/assign

**Comment by saschagrunert** [comment]
Hm, I'm wondering if we really need this now since we have the binary to download directly. :thinking:

**Comment by cpanato** [comment]
we already have that as well we can close this
/close
