### ISSUE TITLE
Don't use one HTTP request per license download

### ISSUE THREAD

**Issue by sbs2001** [kubernetes-sigs/bom#193]
`bom` currently makes almost 500 requests to download various license data. 
```
INFO Read data for 496 licenses. Downloading.     
INFO Sending GET request to https://spdx.org/licenses/GPL-2.0.json 
INFO Sending GET request to https://spdx.org/licenses/Libpng.json 
INFO Sending GET request to https://spdx.org/licenses/blessing.json 
INFO Sending GET request to https://spdx.org/licenses/VSL-1.0.json 
INFO Sending GET request to https://spdx.org/licenses/BSD-4-Clause-Shortened.json 
INFO Sending GET request to https://spdx.org/licenses/OFL-1.0-no-RFN.json 
.....
```

Caching these is not an option on docker based installation.

We could fix this by either:
1. Request SPDX to publish these as an archive Or
2. Cloning https://github.com/spdx/license-list-data/tree/master/json/details 

(2) is something we could immediately do.

**Comment by puerco** [comment]
I think what we want to do here is attach the licenses in an embed fs, this is the issue I opened a while back:

https://github.com/kubernetes-sigs/bom/issues/44

We can have a hack to generate the embed code using the current downloader.

**Comment by puerco** [comment]
I think this is now fixed in https://github.com/kubernetes-sigs/bom/pull/201

/close
