### ISSUE TITLE
downloaded go modules are not being picked up by the go interpreter when bom generate runs

### ISSUE THREAD

**Issue by sandipanpanda** [kubernetes-sigs/bom#202]
#### What happened:
 bom does not leverage the local go cache to look for dependency data while generating SBOM in Cilium image build actions.
 
Generating SBOM describing the source in the Cilium repository
using bom takes, on average, 10 minutes. As a result, the CI
build time increases by 30 minutes if we generate an SBOM
describing the source for all three CI images in Image CI Build
and the CI ultimately fails, throwing an error that no space
is left on the runner.

In theory, if you run "bom generate" in the same environment where you are building (especially after building), all modules should be
there already downloaded, and bom can reuse them. But this does not
happen. One thing that bom will not do is download stuff into your
go directory. If a module is missing, bom will download it to
/tmp/spdx/gomod-scanner/, look at it there, and remove it. Even after
performing a "go mod download" before running "bom generate", the
downloaded modules are not being picked up by the go interpreter
when bom runs.

The downloaded modules are not being picked up by the go interpreter when bom runs: https://github.com/cilium/cilium/actions/runs/3490449396/jobs/5841895937#step:23:1755 for this [workflow file](https://github.com/cilium/cilium/actions/runs/3490449396/workflow#L276).
#### What you expected to happen:
 If bom generate is run in the same environment where you are building (especially after building), all modules should be there already downloaded and bom can reuse them.

#### Anything else we need to know?:
Discussion on this in K8s slack linked [here](https://kubernetes.slack.com/archives/C2C40FMNF/p1667922515647029).

cc @puerco @aanm @nbusseneau

**Comment by nbusseneau** [comment]
Attaching log archive for the workflow run, as it will eventually expire and will be unable from GHA: 
[logs_877851.zip](https://github.com/kubernetes-sigs/bom/files/10115478/logs_877851.zip)
