### ISSUE TITLE
SBOMs support dependency hierarchy for file systems and containers

### ISSUE THREAD

**Issue by bardenstein** [kubernetes-sigs/bom#251]
#### What would you like to be added:
When I generate an SBOM for either a filesystem or a container, I want to be able to see the dependency hierarchy (e.g. the tree relationship between software libraries + versions). 

When I generate SBOMs from bom generate (in either CycloneDX or SPDX), the resulting SBOM files don't show the dependency hierarchies (i.e. the tree relationships between libraries) that other generators do (like the open-sbom-generator). 

I want/need to be able to see, for a given vulnerable library, how it was introduced into an asset.

Ex:
- Dependency 1 (has a CVE)
- - introduced by dep 2
- - - introduced by dep 3
- - - - introduced by dep 4, which is a top-level library / root node. 

#### Why is this needed:
This will allow to more accurate tell developers what software libraries need to be upgrade/replaced, rather than a library that might deeply nested / introduced by another library.

**Comment by puerco** [comment]
Ah this is the issue we discussed on twitter, thanks for clarifying it @bardenstein !

I'll check to see if we can get the structured data and add it if we can, thanks!

**Comment by puerco** [comment]
I'm actually working on this
/reopen
