### ISSUE TITLE
Update asciinema tutorial to use mage not compile-release-tools

### ISSUE THREAD

**Issue by pnasrat** [kubernetes-sigs/bom#367]
/kind documentation

#### What happened:

I was checking out `bom` and the instructions in the asciinema for building the tool are incorrect. 

Following https://github.com/kubernetes/release/commit/9d20564edf038ff1df5625de4d6878eb01fb5e96#diff-6b680f315f5f071ad9a14ff82bfcf67880a01f26e03cafbb8bd2553a5c1b6ddd the asciinema tutorial is misleading as it mentions `./compile-release-tools` which no longer supports bom

Based upon reading the github workflow config the current way for a local build should be `go run mage.go buildBinariesSnapshot`

#### What you expected to happen:

Documentation containing build instructions works

**Comment by cpanato** [comment]
Thanks, are you willing to open a PR to fix that?

**Comment by pnasrat** [comment]
@cpanato I can write a PR to add the Documentation on how to build, and then see if I can get a reasonable version of a screencast if that's something the project wants to retain in the README

**Comment by cpanato** [comment]
i think the screencast we can drop, wdyt @puerco ?
