### ISSUE TITLE
typo maybe?

### ISSUE THREAD

**Issue by SD-13** [kubernetes-sigs/bom#394]
While using the bom cli, I encountered this.
I think [here](https://github.com/kubernetes-sigs/bom/blob/da91ed3ecf02477ff7d88437984bbaadc0c8de84/README.md?plain=1#L97) and in others instances `servers` should be `serves`

**Comment by SD-13** [comment]
@saschagrunert Not sure whom to tag, so tagged you. Please have a look. Thanks!

**Comment by saschagrunert** [comment]
@SD-13 yes this is a documentation bug, do you plan to contribute the fix?

**Comment by SD-13** [comment]
@saschagrunert yes
/assign
