### ISSUE TITLE
Record a new terminal animation

### ISSUE THREAD

**Issue by puerco** [kubernetes-sigs/bom#40]
The animation on the main project page is very outdated. Some of the flags are no longer current and the tools supports a lot more features. 

We need to record a new animation that can show how to generate an SBOM but also how to check the output, etc.

**Comment by jeremyrickard** [comment]
@puerco if it's ok, I can do this one! I'm getting familiar with the tool and updating this seems like a good way to contribute while I'm getting familiar with it.

**Comment by puerco** [comment]
Please @jeremyrickard ! I am terrible at things like this.

**Comment by jeremyrickard** [comment]
I almost have a final version of a new terminal recording. Will open a PR w/ it tomorrow. @puerco do we want to link out to asciinema or convert it to an animated gif and include that in the repo?
