### ISSUE TITLE
Include license list in distribution

### ISSUE THREAD

**Issue by puerco** [kubernetes-sigs/bom#44]
#### What would you like to be added:

The SPDX license list should be included with the bom distribution to avoid downloading it.

#### Why is this needed:

On first run, bom will download [the SPDX license list](https://spdx.org/licenses/). When generating a quick SBOM from a cold start like this the license download can be a bit cumbersome. It can also lead to a CI/CD failure when running bom in a pipeline.

I think we should exploring compiling the license list into a distributable form (a tarball or similar) and shipping it with the binary. I think using [go embed](https://pkg.go.dev/embed) could be the way to go to do this.

**Comment by developer-guy** [comment]
I can take care of that one. Would you mind assigning it to me?

**Comment by developer-guy** [comment]
@puerco https://github.com/spdx/license-list-data

**Comment by developer-guy** [comment]
https://github.com/google/licensecheck

**Comment by sbs2001** [comment]
@developer-guy  I'd like to take a shot at this, if that's cool with you.

**Comment by puerco** [comment]
Awesome, go for it! :tada:
