### ISSUE TITLE
Add a tar-like -C flag 

### ISSUE THREAD

**Issue by puerco** [kubernetes-sigs/bom#52]
#### What would you like to be added:

Add a `-C` flag that allows the user to specify a directory to read files from. Just like tar has -C we should add one just like it.

#### Why is this needed:

Running bom from a directory and adding single files from another is a bit cumbersome. The usual run involves running the utility from the repo root after the build, but usually, files will be stored in a directory, like ./bin or ./output. Adding the files from these results in the paths recorded in the sbom as eg `./output/binary.exe`  which is not clean and could be impractical for verification.

**Comment by cpanato** [comment]
@puerco in this case you will use for example

```shell
$ bom generate -f myfile.txt -C output -o bom.spdx
```

the original way will be 
```shell
$ bom generate -f output/myfile.txt -o bom.spdx
```

**Comment by cpanato** [comment]
made a patch, lets discuss in the pr
