### ISSUE TITLE
ability to generate an SBOM for the images that have been built from scratch base image

### ISSUE THREAD

**Issue by developer-guy** [kubernetes-sigs/bom#74]
#### What would you like to be added:

AFAIK, bom tool couldn’t generate an SBOM for an image that has been built from a scratch image. But, here is the idea, we can find the entrypoint of an image then we can basically run go version -m <binary> to list the deps for that to generate an SBOM, can’t we?

Thanks to @jonjohnsonjr, he already prepared a gist for it.

👉 https://gist.github.com/jonjohnsonjr/66c3b5bc75a2bf69e0524d823e3f7228

#### Why is this needed:

To be able to generate an SBOMs for images that have been built from scratch base image

**Comment by puerco** [comment]
@developer-guy do you have an example of an image that I can use to test this?
