### ISSUE TITLE
Weird timestamp format in SPDX document

### ISSUE THREAD

**Issue by lumjjb** [kubernetes-sigs/bom#98]
#### What happened:

One of the SPDX documents for k8s releases has an incorrect date format:

#### What you expected to happen:

The "Created" field has a datetime format that is inconsistent with commonly used layouts (it looks like the code seems to want to use YYYY-MM-DD as well, which is why it's a little confusing).
```
SPDXVersion: SPDX-2.2
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: kubernetes-v1.21.2
DocumentNamespace: https://k8s.io/sbom/source/v1.21.2
Creator: Tool: k8s.io/release/pkg/spdx
Created: 2021-16-06T13:41:24Z
```
#### How to reproduce it (as minimally and precisely as possible):

```curl -L https://sbom.k8s.io/v1.21.2/source | grep "Created:"```

#### Anything else we need to know?:

N/A. Let me know if this should be opened elsewhere!

#### Environment:

N/A

**Comment by puerco** [comment]
@lumjjb what's wrong with it? What do you mean "commonly used"?  I think the date conforms to the spec, doesn't it?

![image](https://user-images.githubusercontent.com/3935899/173176022-d1665c28-1025-4a1c-bb18-f6eac854f43b.png)

**Comment by puerco** [comment]
Ah got it got. No it used to be a bug at some point, but it was fixed like six months ago in https://github.com/kubernetes-sigs/bom/commit/07a4d4d98859df55a581a2101fe9bf2114f182cf

Thanks for reporting!
/close
